# Experiment metadata
experiment:
  name: "op_lever_game"
  description: "Running Aider in a hand-crafted scaffold with a simple feedback loop."

workspace_dir: null

# Runner configuration - specify which LLM agent to use
runner:
  _target_: runners.aider_scaffold.AiderScaffoldRunner
  model: "gemini/gemini-2.5-flash"
  aider_read_context_fnames: []
  aider_edit_context_fnames: ["lever_game.py", "q_learning.py"]
  aider_run_script: "q_learning.py"
  llm_instructor: False
  llm_instructor_context_fnames: []
  feedback_loop_iters: 1
  feedback_prompt: "Evaluate the results. If you think that the results are good, do nothing. If you think that your implementation has mistakes, fix them."


# Prompt configuration
prompt:
  template_name: "SYSTEM_TASK_EXTRA_METHOD_FROM_LATEX_TEMPLATE"
  contents:
    system_prompt: null
    task: Based on the Zero-Shot Coordination method described in the attached latex block, implement Other-play method to the q-learning algorithm implemented in q_learning.py to learn a ZSC robust policy for the lever-game environment implemented in lever_game.py. Overwrite the q_learning.py file with the implementation of the Other-play method.
    extra_instructions: null
    method_description_header: "Description of the Zero-Shot Coordination method:"
    tex_files: ["op/abstract.tex", "op/background.tex", "op/method.tex"]
    method_description_footer: null
    

env: "lever_game"
algo: "q_learning_1"

extra_workspace_files: []

