# Experiment metadata
experiment:
  name: "obl_cat_dog"
  description: "Running Aider in a hand-crafted scaffold with a simple feedback loop."

workspace_dir: null

# Runner configuration - specify which LLM agent to use
runner:
  _target_: runners.aider_scaffold.AiderScaffoldRunner
  model: "gemini/gemini-2.5-flash"
  aider_read_context_fnames: []
  aider_edit_context_fnames: ["q_learning.py"]
  aider_run_script: "q_learning.py"
  llm_instructor: False
  llm_instructor_context_fnames: ["papers/obl/obl.pdf"]
  feedback_loop_iters: 0
  feedback_prompt: "Analyze the outputs and assess if the code correctly the method described in the prompt. If yes, do not make any changes. If no, make changes to the code to correct the method."


# Prompt configuration
prompt:
  template_name: "SYSTEM_TASK_EXTRA_METHOD_FROM_LATEX_TEMPLATE"
  contents:
    system_prompt: null
    task: Based on the Zero-Shot Coordination method described in the attached latex block, implement Off-Belief Learning (Q-OBL, without the learned belief) method to the q-learning algorithm implemented in q_learning.py to learn a ZSC robust policy for the environment implemented in cat_dog.py. Overwrite the q_learning.py file with the implementation of the Q-OBL method.
    extra_instructions: null
    method_description_header: "Description of the Zero-Shot Coordination method:"
    tex_files: ["obl/abstract.tex", "obl/background.tex", "obl/method.tex"]
    method_description_footer: null

env: "cat_dog"
algo: "q_learning_4"

extra_workspace_files: []
